// Code generated by protoc-gen-go. DO NOT EDIT.
// source: keys.proto

/*
Package pbkeys is a generated protocol buffer package.

It is generated from these files:
	keys.proto

It has these top-level messages:
	Name
	Empty
	GenRequest
	GenResponse
	PubRequest
	PubResponse
	SignRequest
	SignResponse
	VerifyRequest
	HashRequest
	HashResponse
	Key
	ListResponse
	AddRequest
*/
package pbkeys

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Name struct {
	Keyname string `protobuf:"bytes,1,opt,name=keyname" json:"keyname,omitempty"`
}

func (m *Name) Reset()                    { *m = Name{} }
func (m *Name) String() string            { return proto.CompactTextString(m) }
func (*Name) ProtoMessage()               {}
func (*Name) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Name) GetKeyname() string {
	if m != nil {
		return m.Keyname
	}
	return ""
}

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type GenRequest struct {
	Auth    string `protobuf:"bytes,1,opt,name=auth" json:"auth,omitempty"`
	Keytype string `protobuf:"bytes,2,opt,name=keytype" json:"keytype,omitempty"`
	Keyname string `protobuf:"bytes,3,opt,name=keyname" json:"keyname,omitempty"`
}

func (m *GenRequest) Reset()                    { *m = GenRequest{} }
func (m *GenRequest) String() string            { return proto.CompactTextString(m) }
func (*GenRequest) ProtoMessage()               {}
func (*GenRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *GenRequest) GetAuth() string {
	if m != nil {
		return m.Auth
	}
	return ""
}

func (m *GenRequest) GetKeytype() string {
	if m != nil {
		return m.Keytype
	}
	return ""
}

func (m *GenRequest) GetKeyname() string {
	if m != nil {
		return m.Keyname
	}
	return ""
}

type GenResponse struct {
	Address string `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"`
}

func (m *GenResponse) Reset()                    { *m = GenResponse{} }
func (m *GenResponse) String() string            { return proto.CompactTextString(m) }
func (*GenResponse) ProtoMessage()               {}
func (*GenResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *GenResponse) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type PubRequest struct {
	Keyname string `protobuf:"bytes,1,opt,name=keyname" json:"keyname,omitempty"`
	Address string `protobuf:"bytes,2,opt,name=address" json:"address,omitempty"`
}

func (m *PubRequest) Reset()                    { *m = PubRequest{} }
func (m *PubRequest) String() string            { return proto.CompactTextString(m) }
func (*PubRequest) ProtoMessage()               {}
func (*PubRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *PubRequest) GetKeyname() string {
	if m != nil {
		return m.Keyname
	}
	return ""
}

func (m *PubRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type PubResponse struct {
	Pub string `protobuf:"bytes,2,opt,name=pub" json:"pub,omitempty"`
}

func (m *PubResponse) Reset()                    { *m = PubResponse{} }
func (m *PubResponse) String() string            { return proto.CompactTextString(m) }
func (*PubResponse) ProtoMessage()               {}
func (*PubResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *PubResponse) GetPub() string {
	if m != nil {
		return m.Pub
	}
	return ""
}

type SignRequest struct {
	Keyname string `protobuf:"bytes,1,opt,name=keyname" json:"keyname,omitempty"`
	Address string `protobuf:"bytes,2,opt,name=address" json:"address,omitempty"`
	Message string `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`
}

func (m *SignRequest) Reset()                    { *m = SignRequest{} }
func (m *SignRequest) String() string            { return proto.CompactTextString(m) }
func (*SignRequest) ProtoMessage()               {}
func (*SignRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *SignRequest) GetKeyname() string {
	if m != nil {
		return m.Keyname
	}
	return ""
}

func (m *SignRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *SignRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type SignResponse struct {
	Signature string `protobuf:"bytes,1,opt,name=signature" json:"signature,omitempty"`
}

func (m *SignResponse) Reset()                    { *m = SignResponse{} }
func (m *SignResponse) String() string            { return proto.CompactTextString(m) }
func (*SignResponse) ProtoMessage()               {}
func (*SignResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *SignResponse) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

type VerifyRequest struct {
	Keytype   string `protobuf:"bytes,1,opt,name=keytype" json:"keytype,omitempty"`
	Pub       string `protobuf:"bytes,2,opt,name=pub" json:"pub,omitempty"`
	Message   string `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`
	Signature string `protobuf:"bytes,4,opt,name=signature" json:"signature,omitempty"`
}

func (m *VerifyRequest) Reset()                    { *m = VerifyRequest{} }
func (m *VerifyRequest) String() string            { return proto.CompactTextString(m) }
func (*VerifyRequest) ProtoMessage()               {}
func (*VerifyRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *VerifyRequest) GetKeytype() string {
	if m != nil {
		return m.Keytype
	}
	return ""
}

func (m *VerifyRequest) GetPub() string {
	if m != nil {
		return m.Pub
	}
	return ""
}

func (m *VerifyRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *VerifyRequest) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

type HashRequest struct {
	Keytype string `protobuf:"bytes,1,opt,name=keytype" json:"keytype,omitempty"`
	Auth    string `protobuf:"bytes,2,opt,name=auth" json:"auth,omitempty"`
	Message string `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`
	Hex     bool   `protobuf:"varint,4,opt,name=hex" json:"hex,omitempty"`
}

func (m *HashRequest) Reset()                    { *m = HashRequest{} }
func (m *HashRequest) String() string            { return proto.CompactTextString(m) }
func (*HashRequest) ProtoMessage()               {}
func (*HashRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *HashRequest) GetKeytype() string {
	if m != nil {
		return m.Keytype
	}
	return ""
}

func (m *HashRequest) GetAuth() string {
	if m != nil {
		return m.Auth
	}
	return ""
}

func (m *HashRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *HashRequest) GetHex() bool {
	if m != nil {
		return m.Hex
	}
	return false
}

type HashResponse struct {
	Hash string `protobuf:"bytes,1,opt,name=hash" json:"hash,omitempty"`
}

func (m *HashResponse) Reset()                    { *m = HashResponse{} }
func (m *HashResponse) String() string            { return proto.CompactTextString(m) }
func (*HashResponse) ProtoMessage()               {}
func (*HashResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *HashResponse) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

type Key struct {
	Address string `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"`
	Keyname string `protobuf:"bytes,2,opt,name=keyname" json:"keyname,omitempty"`
}

func (m *Key) Reset()                    { *m = Key{} }
func (m *Key) String() string            { return proto.CompactTextString(m) }
func (*Key) ProtoMessage()               {}
func (*Key) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *Key) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Key) GetKeyname() string {
	if m != nil {
		return m.Keyname
	}
	return ""
}

type ListResponse struct {
	Key []*Key `protobuf:"bytes,1,rep,name=key" json:"key,omitempty"`
}

func (m *ListResponse) Reset()                    { *m = ListResponse{} }
func (m *ListResponse) String() string            { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()               {}
func (*ListResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *ListResponse) GetKey() []*Key {
	if m != nil {
		return m.Key
	}
	return nil
}

type AddRequest struct {
	Keyname string `protobuf:"bytes,1,opt,name=keyname" json:"keyname,omitempty"`
	Address string `protobuf:"bytes,2,opt,name=address" json:"address,omitempty"`
}

func (m *AddRequest) Reset()                    { *m = AddRequest{} }
func (m *AddRequest) String() string            { return proto.CompactTextString(m) }
func (*AddRequest) ProtoMessage()               {}
func (*AddRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *AddRequest) GetKeyname() string {
	if m != nil {
		return m.Keyname
	}
	return ""
}

func (m *AddRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func init() {
	proto.RegisterType((*Name)(nil), "pbkeys.Name")
	proto.RegisterType((*Empty)(nil), "pbkeys.Empty")
	proto.RegisterType((*GenRequest)(nil), "pbkeys.GenRequest")
	proto.RegisterType((*GenResponse)(nil), "pbkeys.GenResponse")
	proto.RegisterType((*PubRequest)(nil), "pbkeys.PubRequest")
	proto.RegisterType((*PubResponse)(nil), "pbkeys.PubResponse")
	proto.RegisterType((*SignRequest)(nil), "pbkeys.SignRequest")
	proto.RegisterType((*SignResponse)(nil), "pbkeys.SignResponse")
	proto.RegisterType((*VerifyRequest)(nil), "pbkeys.VerifyRequest")
	proto.RegisterType((*HashRequest)(nil), "pbkeys.HashRequest")
	proto.RegisterType((*HashResponse)(nil), "pbkeys.HashResponse")
	proto.RegisterType((*Key)(nil), "pbkeys.Key")
	proto.RegisterType((*ListResponse)(nil), "pbkeys.ListResponse")
	proto.RegisterType((*AddRequest)(nil), "pbkeys.AddRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Keys service

type KeysClient interface {
	Gen(ctx context.Context, in *GenRequest, opts ...grpc.CallOption) (*GenResponse, error)
	Pub(ctx context.Context, in *PubRequest, opts ...grpc.CallOption) (*PubResponse, error)
	Sign(ctx context.Context, in *SignRequest, opts ...grpc.CallOption) (*SignResponse, error)
	Verify(ctx context.Context, in *VerifyRequest, opts ...grpc.CallOption) (*Empty, error)
	Hash(ctx context.Context, in *HashRequest, opts ...grpc.CallOption) (*HashResponse, error)
	Remove(ctx context.Context, in *Name, opts ...grpc.CallOption) (*Empty, error)
	List(ctx context.Context, in *Name, opts ...grpc.CallOption) (*ListResponse, error)
	Add(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*Empty, error)
}

type keysClient struct {
	cc *grpc.ClientConn
}

func NewKeysClient(cc *grpc.ClientConn) KeysClient {
	return &keysClient{cc}
}

func (c *keysClient) Gen(ctx context.Context, in *GenRequest, opts ...grpc.CallOption) (*GenResponse, error) {
	out := new(GenResponse)
	err := grpc.Invoke(ctx, "/pbkeys.Keys/Gen", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keysClient) Pub(ctx context.Context, in *PubRequest, opts ...grpc.CallOption) (*PubResponse, error) {
	out := new(PubResponse)
	err := grpc.Invoke(ctx, "/pbkeys.Keys/Pub", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keysClient) Sign(ctx context.Context, in *SignRequest, opts ...grpc.CallOption) (*SignResponse, error) {
	out := new(SignResponse)
	err := grpc.Invoke(ctx, "/pbkeys.Keys/Sign", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keysClient) Verify(ctx context.Context, in *VerifyRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/pbkeys.Keys/Verify", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keysClient) Hash(ctx context.Context, in *HashRequest, opts ...grpc.CallOption) (*HashResponse, error) {
	out := new(HashResponse)
	err := grpc.Invoke(ctx, "/pbkeys.Keys/Hash", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keysClient) Remove(ctx context.Context, in *Name, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/pbkeys.Keys/Remove", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keysClient) List(ctx context.Context, in *Name, opts ...grpc.CallOption) (*ListResponse, error) {
	out := new(ListResponse)
	err := grpc.Invoke(ctx, "/pbkeys.Keys/List", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keysClient) Add(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/pbkeys.Keys/Add", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Keys service

type KeysServer interface {
	Gen(context.Context, *GenRequest) (*GenResponse, error)
	Pub(context.Context, *PubRequest) (*PubResponse, error)
	Sign(context.Context, *SignRequest) (*SignResponse, error)
	Verify(context.Context, *VerifyRequest) (*Empty, error)
	Hash(context.Context, *HashRequest) (*HashResponse, error)
	Remove(context.Context, *Name) (*Empty, error)
	List(context.Context, *Name) (*ListResponse, error)
	Add(context.Context, *AddRequest) (*Empty, error)
}

func RegisterKeysServer(s *grpc.Server, srv KeysServer) {
	s.RegisterService(&_Keys_serviceDesc, srv)
}

func _Keys_Gen_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeysServer).Gen(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pbkeys.Keys/Gen",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeysServer).Gen(ctx, req.(*GenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Keys_Pub_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PubRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeysServer).Pub(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pbkeys.Keys/Pub",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeysServer).Pub(ctx, req.(*PubRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Keys_Sign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeysServer).Sign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pbkeys.Keys/Sign",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeysServer).Sign(ctx, req.(*SignRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Keys_Verify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeysServer).Verify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pbkeys.Keys/Verify",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeysServer).Verify(ctx, req.(*VerifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Keys_Hash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HashRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeysServer).Hash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pbkeys.Keys/Hash",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeysServer).Hash(ctx, req.(*HashRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Keys_Remove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Name)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeysServer).Remove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pbkeys.Keys/Remove",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeysServer).Remove(ctx, req.(*Name))
	}
	return interceptor(ctx, in, info, handler)
}

func _Keys_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Name)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeysServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pbkeys.Keys/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeysServer).List(ctx, req.(*Name))
	}
	return interceptor(ctx, in, info, handler)
}

func _Keys_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeysServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pbkeys.Keys/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeysServer).Add(ctx, req.(*AddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Keys_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pbkeys.Keys",
	HandlerType: (*KeysServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Gen",
			Handler:    _Keys_Gen_Handler,
		},
		{
			MethodName: "Pub",
			Handler:    _Keys_Pub_Handler,
		},
		{
			MethodName: "Sign",
			Handler:    _Keys_Sign_Handler,
		},
		{
			MethodName: "Verify",
			Handler:    _Keys_Verify_Handler,
		},
		{
			MethodName: "Hash",
			Handler:    _Keys_Hash_Handler,
		},
		{
			MethodName: "Remove",
			Handler:    _Keys_Remove_Handler,
		},
		{
			MethodName: "List",
			Handler:    _Keys_List_Handler,
		},
		{
			MethodName: "Add",
			Handler:    _Keys_Add_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "keys.proto",
}

func init() { proto.RegisterFile("keys.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 459 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0xcf, 0x8b, 0xd4, 0x30,
	0x14, 0x66, 0x9a, 0x3a, 0xeb, 0xbe, 0xce, 0xc2, 0x12, 0x15, 0x86, 0x41, 0x71, 0x08, 0x88, 0x83,
	0x68, 0xc1, 0xf5, 0xe4, 0xcd, 0x3d, 0xc8, 0x0a, 0x23, 0xb2, 0x54, 0xf1, 0xe2, 0x29, 0xa5, 0xcf,
	0x99, 0x32, 0xf4, 0x87, 0x4d, 0x2b, 0xe6, 0x4f, 0xf7, 0x26, 0x49, 0x93, 0xa6, 0xa9, 0x94, 0x3d,
	0xec, 0xed, 0xfd, 0xe2, 0xfb, 0x5e, 0xdf, 0xf7, 0x35, 0x00, 0x27, 0x94, 0x22, 0xae, 0x9b, 0xaa,
	0xad, 0xe8, 0xb2, 0x4e, 0x55, 0xc6, 0xb6, 0x10, 0x7e, 0xe1, 0x05, 0xd2, 0x35, 0x9c, 0x9d, 0x50,
	0x96, 0xbc, 0xc0, 0xf5, 0x62, 0xbb, 0xd8, 0x9d, 0x27, 0x36, 0x65, 0x67, 0xf0, 0xe0, 0x63, 0x51,
	0xb7, 0x92, 0x7d, 0x03, 0xb8, 0xc1, 0x32, 0xc1, 0x5f, 0x1d, 0x8a, 0x96, 0x52, 0x08, 0x79, 0xd7,
	0x1e, 0xcd, 0xb4, 0x8e, 0x0d, 0x48, 0x2b, 0x6b, 0x5c, 0x07, 0x03, 0x88, 0x4a, 0xc7, 0xf0, 0xc4,
	0x87, 0x7f, 0x09, 0x91, 0x46, 0x15, 0x75, 0x55, 0x0a, 0x3d, 0xc8, 0xb3, 0xac, 0x41, 0x21, 0xec,
	0x1e, 0x26, 0x65, 0x1f, 0x00, 0x6e, 0xbb, 0xd4, 0xd2, 0xcf, 0xee, 0x3b, 0x46, 0x08, 0x7c, 0x84,
	0xe7, 0x10, 0x69, 0x04, 0x43, 0x75, 0x09, 0xa4, 0xee, 0x52, 0x33, 0xa4, 0x42, 0xf6, 0x03, 0xa2,
	0xaf, 0xf9, 0xa1, 0xbc, 0x07, 0x87, 0xea, 0x14, 0x28, 0x04, 0x3f, 0x0c, 0x1f, 0x6a, 0x52, 0xf6,
	0x1a, 0x56, 0x3d, 0xb8, 0xa1, 0x7f, 0x0a, 0xe7, 0x22, 0x3f, 0x94, 0xbc, 0xed, 0x1a, 0x8b, 0xef,
	0x0a, 0x4c, 0xc0, 0xc5, 0x77, 0x6c, 0xf2, 0x9f, 0xd2, 0x5f, 0x46, 0xdf, 0x76, 0xe1, 0xdf, 0xf6,
	0xbf, 0xef, 0x98, 0x5f, 0xc2, 0x27, 0x0d, 0xa7, 0xa4, 0x07, 0x88, 0x3e, 0x71, 0x71, 0xbc, 0x9b,
	0xd2, 0x8a, 0x1f, 0xf8, 0xe2, 0xcf, 0x90, 0x5e, 0x02, 0x39, 0xe2, 0x1f, 0x4d, 0xf7, 0x30, 0x51,
	0x21, 0x63, 0xb0, 0xea, 0x89, 0xcc, 0x2d, 0x28, 0x84, 0x47, 0x2e, 0x06, 0x33, 0xa9, 0x98, 0xbd,
	0x07, 0xb2, 0x47, 0x39, 0x6f, 0x88, 0xb1, 0x3c, 0x81, 0xef, 0xa9, 0x37, 0xb0, 0xfa, 0x9c, 0x8b,
	0x76, 0x80, 0x7f, 0x06, 0xe4, 0x84, 0x72, 0xbd, 0xd8, 0x92, 0x5d, 0x74, 0x15, 0xc5, 0xbd, 0xf5,
	0xe3, 0x3d, 0xca, 0x44, 0xd5, 0x95, 0xb3, 0xae, 0xb3, 0xec, 0x1e, 0xaa, 0x5f, 0xfd, 0x0d, 0x20,
	0xdc, 0xa3, 0x14, 0x34, 0x06, 0x72, 0x83, 0x25, 0xa5, 0x96, 0xc3, 0xfd, 0x30, 0x9b, 0x47, 0x5e,
	0xcd, 0x6c, 0x16, 0x03, 0xb9, 0xed, 0x52, 0x37, 0xef, 0x1c, 0xee, 0xe6, 0xc7, 0x9e, 0x7d, 0x0b,
	0xa1, 0x32, 0x11, 0x1d, 0x9a, 0x23, 0xbf, 0x6e, 0x1e, 0xfb, 0xc5, 0x81, 0x62, 0xd9, 0x3b, 0x89,
	0x3e, 0xb1, 0x7d, 0xcf, 0x59, 0x9b, 0x0b, 0x5b, 0xd6, 0xbf, 0xb9, 0xa2, 0x50, 0xda, 0x38, 0x8a,
	0x91, 0x25, 0x1c, 0x85, 0x27, 0xdf, 0x0b, 0x58, 0x26, 0x58, 0x54, 0xbf, 0x91, 0xae, 0x6c, 0x5f,
	0x3d, 0x2a, 0x53, 0xe4, 0x57, 0x10, 0x2a, 0x59, 0x26, 0x43, 0x03, 0xa4, 0x27, 0xd9, 0x0e, 0xc8,
	0x75, 0x96, 0xb9, 0xc3, 0x38, 0x81, 0x26, 0xa8, 0xe9, 0x52, 0x3f, 0x68, 0xef, 0xfe, 0x05, 0x00,
	0x00, 0xff, 0xff, 0x33, 0xa5, 0x16, 0xee, 0xde, 0x04, 0x00, 0x00,
}
